### ISSUE TITLE
POLAR2018 training

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#1]
## Summary
Three 1.5 hr workshops at POLAR2018
Room can hold 120 people, and is arranged in lecture style

## Advertising Workshops
- [Flyer design](https://drive.google.com/open?id=11EXT3O6KCKY-BMpbL-FPi78cLk7p6bS2)
- [List of places to advertise training](https://docs.google.com/spreadsheets/d/1OiSIzkVsPvorFo9G_ZFqf7EVdYY0vDKd7o9S4_O0XGs/edit?pli=1#gid=0)

## To Dos
- [x] VR to write to Anja Schilling. Request: a time slot on either [6/18 (long session](https://www.polar2018.org/uploads/2/4/6/0/24605948/sidemeeting_overview_monday.jpg)) or [6/19 (short session)](https://www.polar2018.org/uploads/2/4/6/0/24605948/sidemeetings_osc_schedule.jpg)
- [x] MJ to talk to NSF PM to see if we can re-allocate for international travel
- [x] identify trainer team
- [x] identify training topic/ structure
- [x] send short description of training to Anja
- [x] decide whether to have an ADC booth
- [x]  VR check on room size for workshops
- [x] VR create [questionnaire](https://docs.google.com/forms/d/1Hi3fVmQj2I6xTOXnXOX1LLFaqX4Tz-SxRmo1ityEjVo/edit) for participants / Develop a registration form (draft built off of previous applications for trainings)
- [x] [register by 3/31/18 (early bird fee)](https://www.polar2018.org/registration.html) 
- [ ] prepare training materials (issues #45, #46, #47)
- [ ] Advertising trainings (ticket #35)

Staffing:

**Comment by vlraymond** [comment]
workshop description: https://docs.google.com/document/d/1SRyFJMNKxMAtC2WWK2LqpIIwS9dtYFNf5rCn1sYMykg/edit

**Comment by vlraymond** [comment]
Trainer team:

Amber
VR / KM
Matt is available if needed
potential: bring additional staff if there is a booth to man

**Comment by vlraymond** [comment]
VR sent email to Anja about Booth options. Booths are possible, details are scant in the online brochure.

**Comment by vlraymond** [comment]
Some drafts:
[flyer_POLAR2018_8.pdf](https://github.com/NCEAS/arctic-data-outreach/files/1666027/flyer_POLAR2018_8.pdf)
[flyer_POLAR2018_6.pdf](https://github.com/NCEAS/arctic-data-outreach/files/1666036/flyer_POLAR2018_6.pdf)

**Comment by aebudden** [comment]
These look good. Do you have editable versions of these that I could markup? Minor suggestions. Though, also thinking about branding - do we want to create a style for future materials?

**Comment by vlraymond** [comment]
not sure if this will work out ok but I moved copies of the indesign files in to the ADC g'drive, along with images

(https://drive.google.com/drive/u/0/folders/1RAQm3Ged73YQFForw2PThyKy3BeeujNQ)

**Comment by aebudden** [comment]
Need to develop a registration form and add URL to the flyer

**Comment by vlraymond** [comment]
VR check out the following items:
https://github.com/NCEAS/arcticoptions

**Comment by vlraymond** [comment]
can we circle back to this flyer this week? I'd like to have it finalized and start publicizing the workshops asap. Needed next steps:
- [ ] design review
- [ ] design finalized
- [ ] question posed by Amber - do we need a registration form with URL on flyer?

**Comment by vlraymond** [comment]
Kathryn did some create layout clean-up on this poster. https://drive.google.com/open?id=1wnCDHg-Zui87EHgjfoHuPldge5TnHE47

**Comment by aebudden** [comment]
Re the poster some comments:
- Not a fan of the thick blue borders around the title and the learn more
- Opening para: singular training?
- Box 1: Typo Management
- Box 3: typo Publishing
- Footnote: Typo National

Do we have the design files for the Data Fellow Flyer? It might be useful to replicate some of that styling for branding / consistency?

**Comment by vlraymond** [comment]
Pinged Lauren on slack this a.m. to see if she made those fliers and if we could use her files as a template.

**Comment by vlraymond** [comment]
VR got files from Thomas and added them to the [ADC g'drive Printables folder] (https://drive.google.com/open?id=1VPGD9CV1ntrjAEdopzpAqk4tA7ZRPkTn)

**Comment by vlraymond** [comment]
VR emailed Anja Schilling w question about room size of Schwarzhorn A

**Comment by vlraymond** [comment]
Looking at making flight and hotel arrangements and registration for OSC and AOS. We should put out heads together and make a travel plan before Amber leaves next week.

Full Registration: 750 CHF ($799 USD)
Hotel (6/17 to 6/24): 1100 CHF ($1172 USD)

![screen shot 2018-03-06 at 9 01 10 am](https://user-images.githubusercontent.com/7627276/37046538-6f84d09a-211d-11e8-90f3-8b9d77a3ce0e.png)

![screen shot 2018-03-06 at 9 03 27 am](https://user-images.githubusercontent.com/7627276/37046588-9143ca6a-211d-11e8-991e-2ca088aac3c5.png)

![screen shot 2018-03-06 at 9 03 17 am](https://user-images.githubusercontent.com/7627276/37046597-96a2263c-211d-11e8-99f3-fac908e4f96e.png)

**Comment by vlraymond** [comment]
@aebudden this is the latest draft of the POLAR2018 flyer, using the Data Science Fellowship advert as a template.
I have added a .pdf here, I am experiencing some g'drive syncing issues so will update this ticket with the .indd files once I can get g'drive to sync properly :/

[ADC_outreach_POLAR2018_16.pdf](https://github.com/NCEAS/arctic-data-outreach/files/1794920/ADC_outreach_POLAR2018_16.pdf)

**Comment by aebudden** [comment]
Uploaded a new flyer - there were a few things slightly out of alignment. When tidying up, I noticed some inherited issues too so cleaned them at the same time (different box sizes etc). I changed the font type in the lower section as I felt the uppercase titles were hard to read - this might not be better. Few other minor edits.
Note: I had to download the full polar folder since to get the linked out images. Even so, I wasn't able to recreate with the ADC logo since that was a link out to your desktop. Some fonts might not be there for the same reason.

**Comment by vlraymond** [comment]
It's beautiful. 
Making this our "template" for flyers going forward.
Apologies about linking images issues, will clean up my act.

I think this is now ready to go with one remaining question: Should we be directing people to training.arcticdata.io, arcticdata.io/training, or just arcticdata.io

Next step:
- Resolve url question for training content
- VR draft a list of Arctic-specific places to blast out to and share that communication plan here.
- Release this flyer out into the world

**Comment by aebudden** [comment]
@kameyer Can you add this to our training page?

**Comment by aebudden** [comment]
For now, lets only share training.arcticdata.io with participants and not yet as a recruitment venue. Lets use arcticdata.io/training for that. In the case of POLAR 2018 - if there is not a POLAR 2018 page to link to, we should create one on arcticdata.io as we did for the summer workshop. In which case, you will need to change the bottom URL in that flyer.

**Comment by kameyer** [comment]
It looks like the training is listed here on the POLAR18 website: 
https://www.polar2018.org/side-meetings-osc.html

**Comment by vlraymond** [comment]
they are all listed there however we can't easily link to them

**Comment by aebudden** [comment]
Lets create a page where we can provide more full information and then link to the polar2018 one

**Comment by kameyer** [comment]
Webpage Live

**Comment by vlraymond** [comment]
VR create training tickets for each workshop
