### ISSUE TITLE
Finish permafrost posters for PDG

### ISSUE THREAD

**Issue by rzahabi** [NCEAS/arctic-data-outreach#100]
edits to work on at the moment:

a few things to edit:
make the spacing even between all the boxes
make the titles a little bigger
How does it look if you move up all of the titles so it's more centered? (edited)

**Comment by rzahabi** [comment]
Link to canva: 

[https://www.canva.com/design/DAFEc5_11NU/NHwLr_doa65BAdZEM357Tw/edit?utm_content=DAFEc5_11NU&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton](url)

**Comment by nhchavez** [comment]
Looks good, a few things:
- make sure all the pictures of the speakers are in line
- the spacing between the boxes still needs to be exact
- Github: add this issue to the "waiting for feedback" category in the  [projects interface](https://github.com/NCEAS/arctic-data-outreach/projects/1)

**Comment by rzahabi** [comment]
Do you want them in line on one side of the poster?

**Comment by nhchavez** [comment]
I don't think so, I mean: make chandi's head and ingmar's head aligned vertically, and helena is in line with the two others (aligned where the two photos meet)

**Comment by rzahabi** [comment]
> I don't think so, I mean: make chandi's head and ingmar's head aligned vertically, and helena is in line with the two others (aligned where the two photos meet)

Does that look more centered ?

**Comment by rzahabi** [comment]
also do you prefer italicized and bolded title// or just bolded title and the italicized and bolded date?

**Comment by nhchavez** [comment]
I like the bolded title and italicized and bolded date best! Good call!
