### ISSUE TITLE
Make application form for Qualitative course

### ISSUE THREAD

**Issue by nhchavez** [NCEAS/arctic-data-outreach#107]
- copy [this form](https://docs.google.com/forms/d/1U_UhQwu06FwMENz_ZPFQW-AskldH6M68CSUCs4iLgqo/edit) and make it relevant for the fundamentals course
- make sure it's linked to the website
- blast on twitter on september 5th

**Comment by rzahabi** [comment]
![Screen Shot 2022-08-30 at 1 58 04 PM](https://user-images.githubusercontent.com/110846899/187541761-cd374bcd-dccc-4b5c-85e4-d6ae1b6baf0d.png)

**Comment by rzahabi** [comment]
got an error message when trying to do this -- let me know I can work virtual thursday if need be to get this done for you!
