### ISSUE TITLE
Distribute permafrost announcement 

### ISSUE THREAD

**Issue by nhchavez** [NCEAS/arctic-data-outreach#111]
Send out emails.
[Text:](https://docs.google.com/document/d/1jSvJma0Lzs9BMGw-mAMY06bRxMthkirFM7G4UURgk5w/edit)
[Emails](https://docs.google.com/spreadsheets/d/16B40wM3eUYP204guWi5P2ItuCkVwRipaauQNz01vrKo/edit#gid=1348579064):

**Comment by rzahabi** [comment]
first email sent!
