### ISSUE TITLE
Acronyms list for user support

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#13]
linking to FAQ (issue #7), explaining error issues (issues #11)

Purpose: have a list of acronyms used in support documentation or that are useful for interacting with ADC.

doi - digital object identifier
eml - ecological metadata language, read more at https://en.wikipedia.org/wiki/Ecological_Metadata_Language
sid
urn - 
uuid - universally unique identifier

**Comment by erinlynmclean** [comment]
I went through the website and defined all first instances of an acronym on a page - I think that should be sufficient to close out this issue.
