### ISSUE TITLE
ADC social media outreach plan

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#16]
Draft ideas here:
[ADC Social Media Outreach Plan](https://docs.google.com/document/d/1Kzl5cyanzUVnCpNrta45ixfI8vrcsO8rv8_uuTZtMN4/edit?ts=5a6a10ed)

- [x] KM to draft
- [x] VLR added ideas
- [ ] AB to approve

**Comment by aebudden** [comment]
Just added a couple of questions to the document.
