### ISSUE TITLE
48th Arctic Workshop

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#19]
- [x] VR reach out to organizer to see if a workshop /  demo / training is possible
- [x] regardless, VR submit an abstract by 3/16 (link to [abstract submitted on INSTAAR site](http://instaar.colorado.edu/meetings/AW2018/abstract_details.php?abstract_id=44), can be edited if there are further changes from MJ / AB)
- [x] KM submit abstract poster 
- [x] @csjx register by 3/16 http://instaar.colorado.edu/meetings/AW2018/registration.html
- [x] @kameyer logistics (flight, hotel, registration). Hotel needs to be booked by 3/1/18 . See this link: http://instaar.colorado.edu/meetings/AW2018/travel_info/index.html
Registration needs to be booked by 3/16/8
- [x]  KM / CJ crafting [poster](https://drive.google.com/open?id=1e7wlPufwPWY3sszqkuH_oUX3oAQYxN99)
- [ ] VR share draft deck to MJ and AB on 3/30 - see ticket #37 for this deck
- [ ] printing poster (sent off by 4/3 at latest)

## ADC team schedule
VR talk Friday 4/5 - 1:45pm (12 minutes)
KM & CJ Poster session - ?

Staffing:
Chris Jones
Vanessa Raymond
Kathryn Meyer

**Comment by vlraymond** [comment]
VR booked flight, booked hotel. 
VR still needs to :
1 - submit abstract for poster (by 3/16)
2 - register for conference (by 3/16) - http://instaar.colorado.edu/meetings/AW2018/registration.html
3 - book shuttle to Boulder

**Comment by vlraymond** [comment]
KM and CJ have submitted a poster for this.

VR has drafted this [abstract](https://docs.google.com/document/d/1_bDYuwpZ1TCreMhP-6N_yWYZF-09jHcwjjgh7RdPsSo/edit) for a talk on Arctic Data Management. It has the bones of the abstract @mbjones and @aebudden reviewed for APECS talk, with a section added in documenting the historical challenges to data management for Arctic research. NB: it has footnotes...

**Comment by aebudden** [comment]
Some poster feedback: 
- I think the icons are too heavy for the accompanying titles. Can the lines be made thinner?
- Can the QR code be place more as a footnote vs as a primary part of the poster since in itself, it is not giving information?
- Is this the title that was submitted? Otherwise, we likely want to update the title
- Maybe have the data objects count as  677K vs 677,000 so that the font can be larger to match the others?
Now that we have launched more outreach activities, should this poster have a 3rd section? 1) About the Center 2) About the Data 3) About the Community? This could include the fellows, synthesis projects and interns... opportunities for participating.

**Comment by kameyer** [comment]
ADC Poster_March2018 is now available in outreach folders (https://drive.google.com/drive/folders/0B_TUemdsPIhIbktZS2NteWplbms)

**Comment by vlraymond** [comment]
@kameyer @csjx please edit and add your reporting to the below.

## Trip report:
### Mixer - Wed eve
Kathryn and Vanessa attended. In attendance was a small crowd, but tightly cliqued at tables and deep in discussion. We spoke with conference organizers (Wendy and Simon), professors from Gettysburg College who had brought several undergraduate students with them, and a group of PhD students from UMass Amherst Geoscience department who all presented during the conference.

### Day 1 - Thursday (60 - 80 ppl in attendance)
Talks and poster session. Kathryn, Chris, and Vanessa all manned the poster session by taking turns standing in front of the poster, and also circulating around and talking to people with posters.

#### ADC poster:


### Day 2 - Friday (70 - 85 ppl in attendance)
Full day of talks, including the ADC talk at 2pm. 

#### ADC talk:
VR asked audience members who had ever received NSF Polar funding to stand... was about 20 - 25% of audience. Talk seemed well received, 4 people commented to VR afterwards with thank you's for talking about data management and sharing ways ADC supports researchers. KM and CJ both reported audience was engaged and attentive during talk.
 
VR solicited feedback from both: KM suggested refining slides about Synthesis working group (while CJ said those were very good), and KM said that the "overview of ADC" was a good slide and went well while CJ reported that the slide may benefit from being broken up into several slides as he thought audience attention waned a bit on that slide. So... mixed/inconclusive feedback from ADC staff! but good stuff regardless.

### Sidebars:
- Vanessa and Chris had sidebar at poster session with historian and photographer David Witt, says there may be a data rescue project that he worked on with Patrick Webber and Craig Tweedie (however VR pointed out Craig Tweedie has probably archived that project with his own data repositories)
- Vanessa had a sidebar with Eric Coplin from Battelle Ecology who supporrs field logistics for Arctic Research for NEON. Talked about his interest in being able to better support data needs of researchers and to know the landscape of data repositories better. Talked about how extreme weather is destroying a lot of their field sites and they're having to rebuild a lot of them.
- Vanessa and Kathryn had a sidebar with Simon Pendleton and asked him to forward his questions about existing databases for paleo climatology work to support@arcticdata.io

### Follow up:
VR would like to follow up with
- Ruth Heindel to talk about her art about field work used in her slides (KM also wants to reach out)
-  Marilyn Walker to see if there is any data rescue needed for her multi-decadal circumpolar project on creating consensus around an arctic vegetation species list
- Martha Raynolds to see if there is any need for additional or supplemental archiving of her work on the circumpolar arctic vegetation map that ADC could provide. This project currently uses UAF-GINA's glynx data catalog for archiving, however that system does not provide DOIs.
