### ISSUE TITLE
Email communication strategy for interacting with PIs

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#21]
[Current thinking on this issue lives here](https://docs.google.com/document/d/1ZsOn36ScsMTbJYO2hfSyOIJZKWWRihDZR1-75wcxXCQ/edit)

Workflow:
1. pull .csv of NSF awards from NSF award site
2. compare with ADC submissions per award
3. communicate with PIs according to their relationship with ADC (have submitted in the past, have never submitted before, etc) and the status of their award (recently awarded, ongoing, nearing completion, past)

Questions needing answer:
- What is our desired system for emailing PIs and managing a volume of emails?
- How does that system interact with RT for handing off PI questions seamlessly to Support team?
- Is tone of the Email PI document (link at top of this comment) acceptable to ADC PIs and co-PIs?

Needed:
-[] greenlight to start this communication process from AB, MJ.

**Comment by maier-m** [comment]
@irene has built some tools to get new NSF awards and look for NSF awards on ADC.
Also we have gotten some recent feedback from Arctic researchers that they are not aware of the ADC which may push the importance of this communication.

Two strategies may be needed
1. Set up a continous email strategy for new NSF awardees with information as well as potentially set up a skeleton submission for them to access on ADC
2. Retroactively email existing NSF awardees that have not yet submitted to ADC as of now with helpful information

**Comment by isteves** [comment]
Also related (from https://github.com/NCEAS/datamgmt/issues/135)
Link `get_awards` to arcticbot/email updates: provide option for new awardees to populate (some fields) of an EML template of sorts, to get an idea early-on about what’s expected (at least Project level - avoid PI’s copying and pasting NSF abstract to dataset)

**Comment by maier-m** [comment]
Talked with @kameyer 
@kameyer will draft two emails 
1. An initial email from ADC for new NSF ARC awardees
2. An email when NSF ARC awards begin their final year

Data team will draft building the system to collect NSF awards and send emails systematically.

Will get permissions before implementing

**Comment by kameyer** [comment]
KM to draft language for tickets - text to edit in awardBotADC repo
