### ISSUE TITLE
Data Editor - help text

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#22]
- add comments and requests / suggestions in [this document](https://docs.google.com/document/d/1zvnXpcdB0jKf3vU4duf8Ci_1lCbJENzfQYGc2pXDc3Y/edit?usp=sharing)

workflow & timeline:
- [x] CEO team drafts new helper text (by Wed. 02/14)
- [x] Data / Support team reviews (by 3/10)
- [ ] AB reviews & further refines ( by 3/30)
- [x] Dev team reviews (by 3/30)
- [x] ticket created & assigned to dev team to implement final, approved help text in  https://github.com/NCEAS/MetacatUI (by 03/15)

**Comment by vlraymond** [comment]
<img width="1178" alt="screen shot 2018-02-08 at 10 09 35 am" src="https://user-images.githubusercontent.com/7627276/36003098-677bbd14-0ce1-11e8-8990-6719995f71ab.png">

**Comment by vlraymond** [comment]
<img width="1174" alt="screen shot 2018-02-08 at 10 24 13 am" src="https://user-images.githubusercontent.com/7627276/36003126-85930d7a-0ce1-11e8-9052-edc6902bab7c.png">

**Comment by vlraymond** [comment]
needed, from Steph:
"I think it would be helpful to have a very early-on instruction written somewhere about how to add attributes to your data files (clicking the describe button), because this step is separate from the dataset description fields that appear immediately below the files. I hope that makes sense how I've described it.
the workflow of (1) upload your files, (2) fill out the dataset editor, (3) click "describe" to add more info about individual data files wasn't immediately apparent to me"
jesse [3:20 PM] https://github.com/NCEAS/metacatui/issues/440
"Steph’s point is more general than that issue, it’s just not obvious to do click “Describe” and I fear that a lot of submitters won’t unless we make it more clear"


needed, from Jesse:
"we have some serious concerns about the lack of support for custom units on the current version of the new web form and the implications for the data team in terms of processing. the devs are aware of this existence of this issue, but maybe not the extent of the workload it may create on our end. at the least, we’d like to include some Helper language to notify submitters that they should contact us to tell us about any custom units"

**Comment by vlraymond** [comment]
@aebudden @mbjones
what is the best workflow for this? I have started drafting new helper text for the Data Editor release but it should have input from everyone on the team. 

proposed workflow & timeline:
- [ ] CEO team drafts new helper text (by Wed. 02/14)
- [ ] AB reviews & further refines (by Fri. 02/16)
- [ ] Data / Support team reviews (by By Wed. 02/21)
- [ ] Dev team reviews (by By Wed. 02/21)
- [ ] ticket created & assigned to dev team to implement final, approved help text (pls identify appropriate repository for this ticket) (by Fri. 02/23)

**Comment by laurenwalker** [comment]
I think this looks like a good workflow. The repository for the eventual technical Github issue would be MetacatUI [https://github.com/NCEAS/MetacatUI](https://github.com/NCEAS/MetacatUI)

**Comment by vlraymond** [comment]
remember to add in copy person instructions provided by Irene

**Comment by aebudden** [comment]
Can we change the order on the todo? I can't review by 3/10. Perhaps the support team can review first and I will review after.  I will put it on my flight todo list for the weekend.

**Comment by vlraymond** [comment]
Sat down with Jesse, Mitchell, Irene, and Kathryn today and went over the helper text in detail. It's in pretty clean shape right now. Remaining points that are up for debate have comments. I have some final edits for sanity/consistency to do however this is ready for you @aebudden  whenever you can. 

I'll also notify the dev team so they can double check language for consistency with development plans, with EML, and consistency with other repositories.

**Comment by vlraymond** [comment]
from CJ & LW:
"first sentence gets listed, then clickable "..." goes to remaining part of the text"

**Comment by vlraymond** [comment]
VR looked at EML language and dropped pertinent quotes on role, role type in to the document. Not sure how to best describe these roles, may need Data team or Dev team to take lead here.

**Comment by vlraymond** [comment]
Closing this ticket as this language (albeit in truncated / refined form), has been incorporated in to the beta version of  metadata editor now on arcticdata.io
