### ISSUE TITLE
Video guides

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#23]
Topic suggestions

- Attributes
- "Describe" button in "Add files"

**Comment by kameyer** [comment]
### Topics
-[ ] Data Editor

**Comment by kameyer** [comment]
Overview video guide for creating a new submission in Editor

**Comment by aebudden** [comment]
Retaining this pre our conversation about a primer for the Center and recent screencast tutorial activities.

**Comment by erinlynmclean** [comment]
@aebudden @mbjones - let me know if you have any additions to this list, or any topics that should switch categories.

Suggested topics for videos:
- [ ] Demo of how to use the catalog - video

Suggested topics for written explanation:
- [ ] Special requirements of social science data / qualitative data
- [ ] Data science 101 - do these resources already exist? Tend to be long resources. Can we find a self paced course like Interact?
- [ ] Decision tree with aggregated resources like what the SS workshop wanted as a product. Think of the different starting places people are in and suggest resources based on that.
- [ ] What we offer (tools, support, training) 
- [ ] Best practices for data and metadata + Data citation (to the dataONE skillbuilding hub)

**Comment by erinlynmclean** [comment]
Demo script for the catalog video demo has been written and passed to Sarah for her to screencast: https://docs.google.com/document/d/15svgeG01SZDP0JA-HiAlEmIXmLhLr3RMaOuqed2MbB8/edit
@aebudden / @mbjones add any feedback to that document so we can lock down the script before she records everything! :)

**Comment by erinlynmclean** [comment]
@smerickson1 test

**Comment by erinlynmclean** [comment]
https://drive.google.com/file/d/1Jroky9DxxbxY73ASGZPfrKY8ujID3aP4/view - version 2 feedback sent

**Comment by erinlynmclean** [comment]
This version has been through 4 rounds of feedback by me - @aebudden / @mbjones time for you to weigh in! 

[Video](https://drive.google.com/file/d/1WRScR_NO1ThFyHE9NSs25XCygSh3mOkp/view)
[Feedback doc](https://docs.google.com/document/d/1Me2T1SankBw77ULkSpytZGnpMYhG1Yaeyinh7xf9-zU/edit)

**Comment by mbjones** [comment]
I added feedback to the doc. Nicely done @smerickson1 and @erinlynmclean!

**Comment by erinlynmclean** [comment]
@aebudden your turn! :) 

[Video](https://drive.google.com/file/d/1WRScR_NO1ThFyHE9NSs25XCygSh3mOkp/view)
[Feedback doc](https://docs.google.com/document/d/1Me2T1SankBw77ULkSpytZGnpMYhG1Yaeyinh7xf9-zU/edit)

**Comment by erinlynmclean** [comment]
@smerickson1 when you've added the new edits, let us know!
