### ISSUE TITLE
APECS  Online Conference May 16, 2018

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#25]
- [x] VR add to conference schedule
- [x] [draft abstract](https://docs.google.com/document/d/14uax9Pb5CURjqahBIn9f-7dBuYDiIylErdxgPt2_5kQ/edit) 
- [x] feedback from KM, AB, MJ - please add comments to g'doc as suggestions or comments
- [ ] submit abstract by 3/9/18

**Call for Abstracts is 3/9/18** (was extended from 3/2)
Abstracts should be written in English (please contact info@apecs.is if you need other arrangements), no longer than 250 words, and submitted via the form below prior to 2 March 2018 at 22:00 GMT. We will notify you with regards to the success of your abstract by the end of March 2018.
https://apecs.is/events/upcoming-event-highlights/apecs-online-conference-2018.html

**Comment by vlraymond** [comment]
VR add to schedule

**Comment by vlraymond** [comment]
consider video?

**Comment by aebudden** [comment]
Some comments added to the abstract. @mbjones might have additional perspectives.

**Comment by mbjones** [comment]
Comments and revisions added.  Looking good if you address those.

**Comment by mbjones** [comment]
Seems fine because they state that the contributor maintains copyright, and
they will just redistribute for the conference purposes.

Matt
