### ISSUE TITLE
Love Data Week & Endangered Data Week Feb 2018

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#3]
Prior:
- [ ] identify data stories about ADC
- [ ] identify data rescue stories from ADC
- [ ] content schedule created and shared

During:
- [ ] tweet and post on website about rescue and other data stories
- [ ] possibly feature a data set each day of Love Data Week

**Comment by kameyer** [comment]
**Love Data Week Overview**
- Organizing content and activities around themes (instead of days)
- [ ] Telling stories with data
     - Tell us – How is data changing and influencing creativity and storytelling in your community? Share via Twitter thread or send us a blog post.
     - Submit your short-form essay about using data to tell a story (300-600 words) or submit another creative work (visualization, art, video, music, etc.) to be featured on the LDW blog
- [ ] Stories about data
     - What? Write your own data stories or data poem. Tell us about your favorite data set or collection and why you love it (could be personal or professional reasons: research ambition, historic value, scientific/policy/social impact.)
     - How? Submit to our blog via Google Form or Tweet a thread with the hashtags #lovedata18 & #mydatastory
- [ ] We are data: seeing the people behind the data
     - Submit a blog post for the Love Data Week site or share a link on Twitter. Not sure where to get started? Check out the thought-provoking questions below:
          - What is it like to live in data? (h/t Jer Thorp)
          - How does data help us to understand our world?
          - How does data fail to represent us as individuals?
          - How do the biases and limitations of our tools shape the data itself?
          - What does that mean for how we generate information, knowledge, wisdom from data?
          - What is your personal relationship with data? (h/t Jer Thorp)
          - Share an ethical challenge you’re facing with your study or research question.
          - How do the data gathered about us affect our opportunities, the choices we are faced with, and our public personas? (h/t Jer Thorp)
- [ ] Connected conversations
     - Tell us – How is data changing and influencing creativity and storytelling in your community? Share via Twitter thread or send us a blog post.
     - Submit your short-form essay about using data to tell a story (300-600 words) or submit another creative work (visualization, art, video, music, etc.) to be featured on the LDW blog

**Comment by vlraymond** [comment]
new issue created that connects to this - ADC social media outreach plan Issue #16
