### ISSUE TITLE
AGU Fall Meeting 2018

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#31]
[AGU session proposals](https://fallmeeting.agu.org/2018/session-proposals/) due 4/18/18

> NEW THIS YEAR: Session proposals and cross-listed/co-organized sessions will be accepted for the newly formed GeoHealth Section. Also new this year, the Fall Meeting Program Committee invites you to submit Tutorial Talk proposals that improve learning and spark new ways of approaching today’s problems.
> Key Milestones
> **Session and Tutorial Proposal Deadline**: Wednesday, 18 April 2018, 11:59 PM EDT
> **Workshop Proposals Open**: 1 April 2018
> All proposals must be submitted via the online submission website.
> **Abstract Submission Period**: 13 June 2018 – 1 August 2018
> **Abstract and Sessions’ Scheduled Days/Times Notifications Sent:** 1 October 2018.
> For more information, contact the AGU Scientific Program Team.

**Comment by vlraymond** [comment]
Panels
Enjoy a higher level of interaction with presenters. Panels consist of up to eight (8) individuals who will respond to questions from a moderator and audience. Panels could consist of full panels, include a 5-minute talk from each panelist, or have the opportunity for extended Q&A alongside other attendees.

### Idea:
Challenges to Arctic Data Management
comprised of PI to graduate student panel

**Comment by aebudden** [comment]
Challenges to Arctic Data Mgmt sounds like a great topic for a session. Panel sounds good though it maybe harder to get accepted. In which case, does it default to an oral? We will need to include people from outside the ADC so we should start planning this now. Also, we need to submit a workshop to this.

**Comment by aebudden** [comment]
https://fallmeeting.agu.org/2018/session-proposals/

**Comment by vlraymond** [comment]
ideas - 
arctic focused?
provenance focused?

**Comment by aebudden** [comment]
Potential AGU session here: https://docs.google.com/document/d/1KxQth2h020Vsc7BmIbZ2dF2XD76pckx3sD2V78Nr6Os/edit
Very draft. Due 4/18

**Comment by vlraymond** [comment]
As of 4/26/18 for call scientific workshop proposals has not opened

**Comment by vlraymond** [comment]
still waiting for call for workshops to open in order to apply

**Comment by kameyer** [comment]
Call for workshops open. Deadline June 6, 2018
https://fallmeeting.agu.org/2018/scientific-workshops/

**Comment by kameyer** [comment]
Steven's work with semantics could work well in the Data & Rising technology SWIRL theme (https://fallmeeting.agu.org/2018/session-proposals/swirls/)

**Comment by kameyer** [comment]
Proposal Draft, reusing the ESA proposal draft, for review @aebudden https://docs.google.com/document/d/1xnB5avP-iitfTrqVzaM0v-o4yirszyczzsXJ6ekPxiM/edit

**Comment by aebudden** [comment]
Workshop proposal submitted

**Comment by kameyer** [comment]
Although it's not our typical type of session, it might be an interesting opportunity to bring data science into the communication realm/get the word out about the ADC to a new crowd. It could get people thinking differently/be an interesting discussion
