### ISSUE TITLE
ADC swag

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#32]
re-order / new swag needs to be received in hand in advance of June and August training events (POLAR and ESA).  

### send to printer by 5/30/18
ADC team to look over existing ADC swag and determine:
- [ ] swag budget
- [ ] what to re-order (and when, looking at calendar of events)
- [ ] what to update (new content, new design)
- [ ] propose new swag items should be purchased (small button pins, fake tattoos, postcards with conference schedule, cheatsheet guides, other items)

**Comment by vlraymond** [comment]
Needs:
Business cards for VR, KM

**Comment by kameyer** [comment]
Ordered 500 stickers (should arrive by 8 June)

**Comment by kameyer** [comment]
Will bring remaining post cards to POLAR 2018, but decided not worth printing more or creating a new design yet. (During an Arctic team call, there was talk of seeing some in the garbage at the Intl Arctic Workshop) Perhaps post cards aren't the most beneficial swag option for us

**Comment by laurenwalker** [comment]
Are we doing "Keep It Cool" stickers? 😆

**Comment by kameyer** [comment]
Due to the timing of printing (and getting a new potential sticker approved, etc.) we unfortunately won't be able to have a second sticker for POLAR, but maybe in time for ESA in August?
