### ISSUE TITLE
POLAR2018 - advertising workshops

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#35]
(this is a new/ separate ticket. For general POLAR2018 discussion that took place prior to this ticket's creation, see #1 )  
Ok if the flyer is approved I want to start getting the word out about this. I think once the 3/30/18 deadline is passed for the data science training applications, since we're flooding bandwidth with that given it's a tight turn around. So starting 4/1 I'd like to start a push on advertising for POLAR2018 workshops.

- [x] POLAR2018 flyer approved [.indd](https://drive.google.com/open?id=12kT7ZYMFD_DnM-XhQYZfCj9QJTSnens2) / [.pdf](https://drive.google.com/open?id=1n6Bis-LlifNOJfsSAFeD2OAAY0OJNJF8)
- [x] create [contact / advertisement list](https://docs.google.com/spreadsheets/d/1tfP3Pk48Yav0isvA0_yFbEo56H883AxPCZH2nXosyxs/edit#gid=0)
- [x] April -  blast out flyer and or text for workshops
- [x] May -  blast out flyer and or text for workshops
- [ ] early June  - blast out attendee profile survey
- [ ] weekly on June - blast out about workshops

**Comment by vlraymond** [comment]
possibly good idea to remind for registration combined with our blast

**Comment by vlraymond** [comment]
it's posted in APECS calendar
<img width="1043" alt="screen shot 2018-05-03 at 11 26 01 am" src="https://user-images.githubusercontent.com/7627276/39595642-f1a07546-4ec4-11e8-8daf-758c5944a5bb.png">

**Comment by vlraymond** [comment]
blasted out to Cryolist. See it's posted still on APECS. Should be posted to ARCUS again however shouldn't be via VR's personal account in case there are questions

**Comment by kameyer** [comment]
Submitted to ARCUS events 6/1/2018
