### ISSUE TITLE
Advertise RFP

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#38]
[RFP .doc](https://drive.google.com/open?id=0B7aTdNApBd6zSTJjZThXbVVwekJBWDVxTDhTaEpCNnh5czNJ)
[tracking postings/outreach](https://docs.google.com/spreadsheets/d/188k4sQjA79lcYAjxG5vdfhLv8JWDw7_XRi7N6BwAHBE/edit#gid=0)

## To dos:
- [x] put on arcticdata.io
- [x] put on NCEAS site
- [x] tweet from @arcticdatactr
- [ ] Data highlight on Synthesis WG to coincide with RFP
- [ ] reminder tweet from @arcticdatactr
- [ ] blast to Arctic listservs

## Timeline
Deadline: May 23, 2018  
Decisions: announced in early July 2018  
Work: to start by October 2018  

## General timeline:
To start blasting in April 2018, after call for applications for data science training and simultaneously with POLAR2018 advertisements

**Comment by kameyer** [comment]
Posted call for proposals as Update on IARPC Collaborations Member space on 04/10

**Comment by vlraymond** [comment]
VR  re-organize spreadsheet to include frequency of commnications

**Comment by vlraymond** [comment]
hold.
