### ISSUE TITLE
APECS Int'l Online Conference - prep for talk

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#39]
May 16th, 2018

Abstract accepted.

*
_email from organizers_
> Title - Maximizing Impact: The Case for Metadata 
> Presentation type - Oral Presentation . 
> Session3  
> 
> Time slot - 16:30-16:45 GMT  
> We will contact you shortly with dates of practice sessions so that you can familiarise yourself with our webinar system in advance of the conference. We look forward to receiving your confirmation and do not hesitate to contact us at info@apecs.is with any queries.  
> Kind regards,  
> Yi-Ming, Gan  
> On behalf of APECS International Online Conference 2018 organizing committee

**Comment by vlraymond** [comment]
email received on 4/25/18
> Dear participants in the APECS Online Conference on 16th May, 2018
> 
> We are organising training sessions, so you can test your computer setup, make sure that your presentation format works and check your audio to confirm that you or any audio you will be playing can be heard (you will need a microphone). Please could you sign up by 28th April 10pm GMT to any times on this doodle poll that would be convenient for you to join a training session: https://doodle.com/poll/5bnk7r8ci42tf6nq
> 
> Please contact me asap at clare.eayrs@nyu.edu if none of these times work for you. The system is very straightforward if you are using Mac or Windows OS. Please could you let me know if you are using Linux as there is some extra information I will need to send you before the training session to make sure you can share your screen.
> 
> The training will be web-based, using ZOOM, which we will be using to stream the conference. You will be able to share your screen, so you can have full control of your slides/other media. We will send you details of how to join the training session once we have arranged the schedule.
> 
> If your presentation is not finished, then please make sure that you have a draft in the same format of your final presentation, so that you can test screen sharing and make sure that any videos/links/anything else you may wish to use works.
> 
> Don't hesitate to contact me if you have any questions about anything
> Best wishes
> Clare
> On behalf of the APECS Online Conference Organising Committee

**Comment by vlraymond** [comment]
@aebudden do you want someone else at ADC to take this talk scheduled for 5/16? If so there are training sessions happening this week, and we should notify the organizers of the name change.

If not, I should notify them that this talk is canelld.

**Comment by vlraymond** [comment]
https://docs.google.com/document/d/14uax9Pb5CURjqahBIn9f-7dBuYDiIylErdxgPt2_5kQ/edit

**Comment by vlraymond** [comment]
AB - Should be MJ?

**Comment by aebudden** [comment]
@mbjones I have a day off this day (kids school camp trip). can you take this?

**Comment by kameyer** [comment]
KM presented (https://docs.google.com/presentation/d/1jgrmosJbDhnvesTatAsoZzqlCOM1T6loiung-jUUGvQ/edit#slide=id.g395f0ab614_0_0). All presentations were recorded - should be available on APECS website soon.
