### ISSUE TITLE
ESA 2018 - logistics

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#41]
Logistics to do's
- [ ] KM confirm details with AB on travel
- [x] KM register, secure hotel and lodging
- [ ] bulk up on swag (issue #32)
- [ ] coordinate shipping of materials down to ESA / hotel

**Comment by vlraymond** [comment]
- 6 orgs across 4 booths.
 - 3 booths have paired orgs (cafe / shared space / ), fourth booth is a "stand alone" for workshops, demos and talks. There will be a schedule for talks that include outside organizations.

- messaging will be really important.

AB to check on full registrations vs booth registrations

**Comment by kameyer** [comment]
Early bird deadline: June 14

**Comment by kameyer** [comment]
Kathryn registered for ESA

**Comment by kameyer** [comment]
Kathryn booked hotel for Sat 8/5 - Fri 8/10 in NOLA
