### ISSUE TITLE
Fellow Feedback

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#43]
gather feedback from existing fellows to incorporate in to next cohort planning and prep

**Comment by aebudden** [comment]
Develop a survey that can be used for this cohort and future cohorts?

**Comment by vlraymond** [comment]
- dominic and stephen leave first (end of April?)
-  Irene, Rachel, Steph
- emily (July)

survey topics:
1. perceived development
2. match up questions with an onboarding survey with this exit survey

**Comment by kameyer** [comment]
Draft Questions: (coming soon)
Timeline: Get survey to fellows by June 1

**Comment by kameyer** [comment]
@aebudden could please you take a look at the draft questions (link above) and provide your  feedback/suggestions? Thanks

**Comment by kameyer** [comment]
The feedback form was sent to all Fellows. 6/12/2018 Requested all responses by 6/29/2018 (or by the end of their fellowship period)

**Comment by jagoldstein** [comment]
awesome! thanks so much @kameyer .

BTW, Steph mentioned to me that on her call with Matt yesterday he told her that he plans to _try_ to meet with all the fellows individually to debrief about the program. If this happens, I hope Dom and Steven are included too, even though their fellowships have already ended.

**Comment by kameyer** [comment]
Fellow Feedback Summary: https://docs.google.com/document/d/1oos-ak-mLWSbzvgI9Cas0AJhJDrHeTV-CvTFShYdW7c/edit?usp=sharing

**Comment by aebudden** [comment]
This feedback period has closed. We now have a survey and process in place.
