### ISSUE TITLE
Improve "Submission" on arcticdata.io

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#44]
Goals:
- set better expectations using "Submission" and "Q&A" pages
- clear / clarification on expectations (useful for our team and for users)
- resource for data team
- quickly changeable

Document Structure:
- overview
-> links to examples
--> links to broader / deeper explanations
---> links to EML

Example:
[Dataverse Project - User Guide](http://guides.dataverse.org/en/4.8.6/user/)

Proposed review process:
- [ ] Data team creates document
- [ ] Outreach team assists with wordsmithing
- [ ] MB approves
- [ ] Marc Steiglitz reviews / approves

Needed:
- [ ] pop up to present the support documentation

What is the difference between DMP template for ADC and "Submission":
- Submission doc is more in depth
- DMP template can link to sections of the submission doc

**Comment by vlraymond** [comment]
MJ - requests we update submissions page on arcticdata.io sooner rather than later and iteratively as opposed to perfectly.

**Comment by mbjones** [comment]
The updates look great.  Let's try to make it more readable/approachable, and include some images and figures as needed.

**Comment by aebudden** [comment]
@erinlynmclean This is largely out of date and you have been working on web page updates. However, I am not closing the issue since there may be some elements that are worth considering. Please review and either close or integrate pieces into new issues you are building.
