### ISSUE TITLE
POLAR2018 - DMP session

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#45]
# Session: Data Management Planning
_(what we said we were going to do)_
- Introduction to the Arctic Data Center
- Data Life Cycle
- NSF Standards and Policies
- Tools for Writing a Data Management Plan

# Some pre-existing resources
### Why create a DMP
- [ESIP Commons: Why Create a Data Management Plan?](http://commons.esipfed.org/node/1439)

### Elements of a DMP
- [ESIP Commons: Elements of a DMP](http://commons.esipfed.org/node/1442)

### What is a Data Management Plan?
- [Data Management and Curation Working Group (DMCWG) - What is a Data Management Plan? ](https://zenodo.org/record/159727)

### DMP guidance
- [Digital Curation Centre - Data Management Planning Guidance for Postgraduate Researchers. ](https://zenodo.org/record/28545)

### Data Preservation
- [Mozilla: Your Data Can Live Forever](https://mozillascience.github.io/working-open-workshop/data_reuse/)

### Hands on-  ADC's NSF DMP tool
- [DataOne's Education Module on DMP Tool](https://www.dataone.org/education-modules)

**Comment by kameyer** [comment]
Workshop session on June 19 had 15-17 participants. The workshop was over the lunch period and difficult to find on the schedule (huge conference with a lot going on) - so the attendance number can overall be considered a success.

Attendees commented that they appreciated learning about DMP resources (i.e., DMPTool), as they were not aware these helpful online tools existed.

Notes for future DMP workshops: Use concrete examples to demonstrate the concepts and level of detail to include in the DMP sections (esp. for data type and format sections). Ask questions to attendees from the start (i.e., have you created a DMP?/have you used or heard of the DMP tool? etc.); Will improve advertisement plan in the future, too.  

Condensed version of the presentation slides are now posted and available on our website POLAR 2018 training page (https://tinyurl.com/ycynwl5l).
