### ISSUE TITLE
ESA Lightning talk

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#50]
@aebudden do you want to change the presenter name on this lightning talk to @kameyer? Or cancel? Cancellation or abstract changes need to take place by tomorrow 2:00pm pacific

https://docs.google.com/document/d/1NuWbPEGJSXB1HUqqf33abEvSuJRzQ6luwU2Hg5HJfYw/edit

https://docs.google.com/presentation/d/1ONF4HWU-y8eQB-MomKsyJDl8MPvKwQ8yGAbXGBMKp4U/edit

###

email from organizers:
"Congratulations! Your abstract for an Ignite presentation has been accepted for the 2018 ESA Annual Meeting in New Orleans, Louisiana. 

Abstract ID#: 70535 
Password: 954420 
Abstract Title: "How to Leave a Trail (a.k.a. Skills for Effective Data Preservation)"
INS 19: "Skills and Knowledge for Data-intensive Ecological Research across the Data Lifecycle" (#14316) 
Wednesday, August 8, 2018 
3:30 PM - 5:00 PM

Editing Your Abstract 

Abstract editing is now available. You may edit your abstract through Tuesday, May 1 at 5:00 pm Eastern Time (2:00 PM Pacific). 

Attention students! This is your final opportunity to edit your coauthor list. Please make sure important names (i.e. your advisor) appear as they should in the program. We will be unable to edit coauthors after the editing period has ended. 

How to Edit Your Abstract 

1. Please follow the first link to VIEW your abstract as it will appear in the preliminary program: 

http://eco.confex.com/eco/2018/preliminaryprogram/abstract_70535.htm 

2. If you need to edit your abstract, follow the second link below to do so. 

http://eco.confex.com/eco/2018/inspire/extra/index.cgi?EntryType=Paper&username=70535&password=954420 

Changes will not appear at the preliminary preview (the first link) right away, but rest assured any changes that you make using the editing interface will appear in the preliminary program the next time we update the website (usually within a day or two). 

Cancellation Deadline

This is a reminder that the deadline to cancel your presentation without risk of penalty is May 1. 

ESA is unable to provide financial support to speakers. If you cannot travel to present in person, you should cancel this abstract before May 1. We encourage you to cancel by May 1 or plan for an alternate presenter if there is strong uncertainty about your attendance. If you become aware that you will be unable to attend after May 1, we encourage you to find a substitute presenter if possible.

If you cancel after May 1, it causes gaps in the final program, which are a serious disruption for attendees. For this reason, you may be subject to the penalty listed in the original call for abstracts, which is a $50 penalty for late cancellations.

There is a potential one year presentation ban for no shows (failing to appear for your scheduled presentation at the meeting, without any notice provided). For more information, visit: https://esa.org/neworleans/cancellations/ 

Please notify Jennifer Riem (jennifer@esa.org) as soon as possible if you need to cancel your presentation. 

One Presentation Rule 

In order to broaden participation, you may give only ONE presentation (any talk or poster that includes an abstract) at the meeting unless one of your presentations is primarily about education or outreach. Inspire ESA presentations are exempt from this rule for 2018. 

Meeting Registration

All speakers must register to attend the meeting. Submitting an abstract does not register you for the meeting. Registration is not waived or reduced for speakers. Meeting registration and housing are now available through the meeting website: https://esa.org/neworleans.

One of the benefits of ESA membership is lower registration rates for the Annual Meeting.

Please email Maya Sohn (registrar@esa.org) with any specific questions about registration.

International Attendees

If you require a letter of invitation, you may print an automatically generated letter at your convenience by following this link and scrolling to the bottom of the page: http://eco.confex.com/eco/2018/inspire/extra/index.cgi?EntryType=Paper&username=70535&password=954420

If your institution requires more specific language in the letter, please contact Maya Sohn (registrar@esa.org).

If you have other questions about visas, we have additional information here that you my find helpful. 

https://esa.org/neworleans/letter-of-invitation-visa-information/

Congratulations on your acceptance. Please let us know if you have any questions. We look forward to your participation this year!

Timothy Schowalter 
2018 Program Chair 
TSchowalter@agcenter.lsu.edu

Jennifer Riem 
Program Coordinator 
jennifer@esa.org 
Attachments: None"

**Comment by aebudden** [comment]
There are many lessons to be learned from fairy tales. In this Inspire talk we’ll revisit such classics as Hansel and Gretel and Jack and the Beanstalk to talk about effective data preservation. What can Hansel and Gretel’s trail of breadcrumbs through the forest teach us about retracing our steps in our own research? How can Alice in Wonderland’s White Rabbit and Cinderella’s glass slipper serve as cautionary tales about data preservation for the research community? Join us for some tips, tricks, pros, and cons of effective data preservation.

**Comment by vlraymond** [comment]
AB assessment is to hand this talk to Matt to give.

**Comment by aebudden** [comment]
@mbjones You are not slated for an ignite in this session (led by Steph H and I). Can you take this?

**Comment by kameyer** [comment]
Edited the Abstract
Title: The Case for Metadata 
In research, things don't always go as planned. But good metadata practices can help you counteract, and keep track of, your project's unexpected moments. Come learn about the importance of metadata and discover ways you can benefit from maintaining it. With good metadata, if you put in the effort, you can reap the reward.

**Comment by vlraymond** [comment]
KM submitted new abstract and is now listed as the the presenting author
