### ISSUE TITLE
Ensure Non-NSF funded submissions languages is correct

### ISSUE THREAD

**Issue by maier-m** [NCEAS/arctic-data-outreach#61]
Need to make sure our language surrounding non-nsf fundend submissions is accurate in https://github.com/NCEAS/arctic-data-outreach/blob/master/Website_Pages/Data_Submission.md

See 
1. https://github.com/NCEAS/arctic-data-outreach/blob/master/Website_Pages/Data_Submission.md#publication para 2
2. https://github.com/NCEAS/arctic-data-outreach/blob/master/Website_Pages/Data_Submission.md#guidelines-for-large-data-packages

Can create a new section for Non-NSF funded submissions if needed

**Comment by mbjones** [comment]
I reviewed the text, and the policy looks good.  I made minor language tweaks, and indicated that people should contact support for questions on non-NSF datasets.

**Comment by jagoldstein** [comment]
https://arcticdata.io/submit/ updated
