### ISSUE TITLE
join https://fairsharing.org/

### ISSUE THREAD

**Issue by maier-m** [NCEAS/arctic-data-outreach#64]
ADC should be entered here https://fairsharing.org/
This is requirement 7 for being a PLOS ONE data repository http://journals.plos.org/plosone/s/data-availability#loc-repository-inclusion-criteria

KNB already has an entry here https://fairsharing.org/FAIRsharing.jjka8c

**Comment by jagoldstein** [comment]
I received this email today:

"PLOS journals would certainly consider KNB to be an acceptable repository for authors to use to meet our data sharing requirement.

All the best,

Nick Simon | Publications Manager, PLOS ONE"

**Comment by mbjones** [comment]
Awesome, @jagoldstein.

It would probably be good for us to push this for both KNB and ADC with multiple journals.  I've tried to register them at multiple repository registries, but it seems that every time I turn around there's a new registry/requirement. We used to be listed for Scientific Data, but not sure if we still are.  There's also an initiative to have multiple journals support a common list that is maintained at COS.  I think it woul dbe great if you can continue to follow up with these if you encounter such needs.

**Comment by kameyer** [comment]
@jagoldstein do I just send emails to Fair Sharing and journals asking if ADC can be registered as a data repository?

**Comment by jagoldstein** [comment]
@kameyer it's unclear to me, but yes, that's my best guess. See Matt's comment above (https://github.com/NCEAS/arctic-data-outreach/issues/64#issuecomment-404907761); please ask for the KNB as well.

**Comment by kameyer** [comment]
Sent an email to contact@fairsharing.org inquiring about the steps to joining the FAIRsharing network 10/24

**Comment by aebudden** [comment]
This issue is still active. KNB is listed, Arctic is not.

**Comment by erinlynmclean** [comment]
Sent an email to contact@fairsharing.org inquiring about the steps to joining the FAIRsharing network 5/18

**Comment by erinlynmclean** [comment]
They got back to me and I created an account using the arcticdatactr@gmail.com email address. 

Next step: 

- [ ] create the record on the site using their system. 

"Adding and editing a record in FAIRsharing is easy. Information on how to do this can be found here: https://fairsharing.org/new/"

**Comment by mbjones** [comment]
I don't know what that email address is.  Could you please use one of our arcticdata.io addresses instead, preferably a list that can go to multiple people? We can easily create a new list address for this type of subscription if needed.

**Comment by erinlynmclean** [comment]
The reason I had made that email was that I needed a gmail account to sign into flickr...now I have a few logins tied to it (Flickr, Vimeo, and now this). I don't know if I'd be able to "Sign in with Google" with an arcticdata.io address but down to be proven wrong.

No email actually goes to that gmail account - I have it set up to forward all emails to me. I can also set it up to forward all emails (and there are none) to an arcticdata.io address if that makes more sense.

**Comment by erinlynmclean** [comment]
Submitted the record to FairSharing 5/28, waiting for approval.

**Comment by erinlynmclean** [comment]
Record added - can be found here: https://fairsharing.org/biodbcore-001529/

**Comment by mbjones** [comment]
Congrats and thanks, @erinlynmclean !

I looked over the entry quickly -- there's a few things we should discuss, including the start year (NSF actually started funding the facility much earlier than 2016 with CADIS, so we have data form much earlier projects), and the standards and metrics that we use/follow. We should get some of the other metadata standards that we use listed, as well as the data, FAIR, and metrics standards (COUNTER) that we follow. (It would be great to update our KNB entry with these details as well @jeanetteclark ).

**Comment by erinlynmclean** [comment]
Sure, I'll add discussing this to Friday's Arctica agenda!

**Comment by erinlynmclean** [comment]
I cross referenced the record at re3data and added a bunch of things - tagging in @jeanetteclark to add anything else I may have missed. username is arcticdatactr. 

https://fairsharing.org/biodbcore-001529/
