### ISSUE TITLE
January Training Call for Applicants

### ISSUE THREAD

**Issue by kameyer** [NCEAS/arctic-data-outreach#65]

**Comment by dmullen17** [comment]
@kameyer I can't attach a csv file in Github so i'll just add the R code I used to generate it.  You can change the date if you want (I just pulled the past 6 months).  If it's a pain to run that (the `datamgmt` package can be troublesome) I'm happy to share the file elsewhere, but it might be interesting to run the code / mess with it!  

```
# Install the necessary packages 
devtools::install_github("NCEAS/datamgmt")
install.packages("tidyverse")
library(datamgmt)
library(tidyverse)

# get all awards from "03/04/2018" 
# you can the date using "MM/DD/YYYY" format 
new_awards <- get_awards(from_date = "03/04/2018") %>% 
  as.tibble() %>%
  select(awardee, date, startDate, expDate, everything()) %>% # re-order the columns 
  arrange(desc(date))  # sort by descending date 

View(new_awards)

# Save to Desktop 
write.csv(new_awards, "~/Desktop/new_awards.csv", row.names = FALSE)
```

**Comment by kameyer** [comment]
KM emailed PIs who received NSF award between January 2018 - September 4, 2018

**Comment by kameyer** [comment]
Documents: https://drive.google.com/drive/folders/1xeGGhhP5BIxsDkqWIoJh_mFhndR9NdBQ?ogsrc=32
