### ISSUE TITLE
update advisory board with photos on web

### ISSUE THREAD

**Issue by mbjones** [NCEAS/arctic-data-outreach#66]
I just restructured the Advisory board section of the web site.  I think we should also add photos, and restructure the page using the same layout as the section above for team photos.  So, for each advisory board member, please:

- [ ] add a photo in the standard size and aspect ratio using the circular layout
- [ ] link their name to their bio
- [ ] indicate their term of service

It would also be nice to add a top-level menu item in the site to the Science Advisory Board under 'About'.

**Comment by dmullen17** [comment]
[] remove Kathryn from About page as well

**Comment by CSemnacher** [comment]
@mbjones, can you let me know how the page looks? Do you have any suggestions for further edits? 

https://arcticdata.io/team/#science-advisory-board-identifier

**Comment by mbjones** [comment]
Looks great, thanks! @aebudden or @laurenwalker might have suggestions, but if not, please close this ticket.  Thanks.

**Comment by laurenwalker** [comment]
Looks good to me!
