### ISSUE TITLE
draft external-facing FAQ for arcticdata.io

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#7]
### Existing INTERNAL (data-team only) FAQ:

- https://nceas.github.io/datateam-training/using-rt.html#other-faqs
- https://github.nceas.ucsb.edu/KNB/arctic-data/blob/master/datateam/How_To/RT/email_templates.md
- https://nceas.github.io/datateam-training/reference/pi-faqs.html
- https://nceas.github.io/datateam-training/reference/email-templates.html

### New EXTERNAL (user-facing) FAQ
[Draft user-facing FAQ](https://github.com/NCEAS/arctic-data-outreach/blob/master/FAQ.md) - for review from Data team

next steps:
- [x] VR create .md with ToContents
- [x] VR share FAQ.md to data team for review and additions (was done on 4/18)
- [x] data/support team provides feedback by 4/30
- [x] Merge commits for FAQ and Submission page (5/4)
- [ ] VR / KM add FAQ to website, see if dev team has any better ideas for integration beyond just the FAQ page (5/13)

**Comment by vlraymond** [comment]
FAQ and helper text should link to EML FAQ
https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/eml-faq.html

**Comment by vlraymond** [comment]
VR make this into a .md and then share out

**Comment by vlraymond** [comment]
add table of contents

**Comment by vlraymond** [comment]
@jagoldstein I guess I'd just make a new branch w your edits. 

No worries, I didn't ask you all to look at it until just y'day because I felt like there was a lot on your plate with testing the editor, new fellowship applications, etc.

**Comment by jagoldstein** [comment]
ok @vlraymond I submitted a PR with my edits to merge my branch to the master

**Comment by vlraymond** [comment]
So I reviewed Jesse's PR. I don't think I have write permissions to commit the PR (or II am doing this wrong)... anyways so it's reviewed but not committed. @mbjones

**Comment by kameyer** [comment]
great, thanks @jagoldstein!

**Comment by kameyer** [comment]
The FAQ page on the website has been updated with the improved content (https://arcticdata.io/q-and-a/)

**Comment by jagoldstein** [comment]
@kameyer this is great, thanks! I just noticed one minor formatting issue:

<img width="851" alt="screen shot 2018-05-15 at 2 39 02 pm" src="https://user-images.githubusercontent.com/18270215/40084976-cb3409c6-584d-11e8-8b8b-859ae8eb2dbf.png">

these 3 hyphenated points should each be on a separate line (bulleted), or simply turned into a sentence with a list.
