### ISSUE TITLE
Training site overhaul

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/arctic-data-outreach#74]
- [x] Fix dead links on https://arcticdata.io/training/
- [ ] Add Google Analytics to https://training.arcticdata.io/
- [x] Link https://training.arcticdata.io/ to https://arcticdata.io/training/ so t hat people can access it from the website

**Comment by smerickson1** [comment]
test

**Comment by erinlynmclean** [comment]
@laurenwalker I don't know how to add Google Analytics to training.arcticdata.io - any help with that would be great!
