### ISSUE TITLE
Create portals lesson for ADC training

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/arctic-data-outreach#78]
Create a module for the Artic Data Center training about the portals:
-Why portals are great
-How to use them
-How to create one and add data

Create this module for both in person and asynchronous online learning.

**Comment by erinlynmclean** [comment]
Working on this, starting with the text from ESS-DIVE's portal documentation.

https://docs.google.com/document/d/1TYKiauTOMG-Av-fUz7S5D6a4TDFIkhYHNYDrSMlMDZY/edit#

**Comment by smerickson1** [comment]
https://drive.google.com/file/d/1JtizwYPDCq-gC6KP1IdKFIcfTU9Q0Ohf/view in review

**Comment by erinlynmclean** [comment]
Finished for D1, sent @jeanetteclark updated images to add to the ADC bookdown.
