### ISSUE TITLE
New Website page - FAIR principles

### ISSUE THREAD

**Issue by erinlynmclean** [NCEAS/arctic-data-outreach#85]
How does the Arctic Data Center comply with the FAIR principles? Might be nice to have a page on this on the about page or something like that...

**Comment by aebudden** [comment]
Link to FAIR page is within  '[working with data](https://arcticdata.io/working-with-data/)' but  page does not exist /  has  not been published. 
- [ ] Check for existence of content and either
- [ ] 1) publish or
- [ ] 2) remove reference to FAIR from working with data
