### ISSUE TITLE
Blog  article for sensitive data types

### ISSUE THREAD

**Issue by aebudden** [NCEAS/arctic-data-outreach#87]
[Blog piece](https://docs.google.com/document/d/1Y3sB6mmRZMMmpqgLZsvvLRgnvz4usCfxUmU9xrdpkEM/edit) written.  Needs review and sign off from 

- [ ] @mbjones and 
- [ ] @aebudden

- [ ] Need  to coordinate announcements with MetacatUI release. Likely  week  of 1/24
- [ ] Newsletter piece as well as blog piece
- [ ] Promote via social media

**Comment by mbjones** [comment]
I added an initial set of comments @nhchavez -- have a look. Overall this is a good start. I think the piece needs more depth, and to develop a thesis. Think of it less as a news item and more of a thought piece with a message -- the "news" is incidental to the message. I think the message should be along the lines of: "ADC improvements begin the process to embrace deep transparency in data ethics" -- we should discuss several alternatives on what this message might be that we are trying to communicate.

**Comment by aebudden** [comment]
I moved the issue back to in progress as I think the feedback provided by Matt would be great to include before another level of review.

**Comment by nhchavez** [comment]
Blog piece updated Feb 2nd, waiting for review from @aebudden and @mbjones
