### ISSUE TITLE
Community wide survey

### ISSUE THREAD

**Issue by aebudden** [NCEAS/arctic-data-outreach#88]
Develop  community wide survey to understand perspectives, awareness and satisfaction associated with the Arctic Data Center. Collaborate  with  other organizations  to have a more comprehensive set  of questions  and  reduce survey  fatigue from participants. Survey needs to be  released  in Yr1.

Current brainstorming [document](https://docs.google.com/document/d/1Mi-zOeGsepcZ9iZDNWoGUPPmGaKVK1olZUfks_fWHJE/edit)

**Comment by nhchavez** [comment]
Ready for review from @aebudden 
https://docs.google.com/document/d/1Mi-zOeGsepcZ9iZDNWoGUPPmGaKVK1olZUfks_fWHJE/edit#

**Comment by nhchavez** [comment]
2-22-22 
Ready for feedback from Matt and Amber
