### ISSUE TITLE
Draft 10 tweets 

### ISSUE THREAD

**Issue by rzahabi** [NCEAS/arctic-data-outreach#95]
Drafted in buffer; already have until thursday. Link to buffer: [https://publish.buffer.com/profile/5eb0547ae84da031eb4f7313/tab/queue](url)

**Comment by nhchavez** [comment]
Looks great! A few comments:
- for today's tech tuesday tweet, the laptop picture is fine, but im wondering if we could get something more engaging. This might be a case where it's better to use a funny gif with a cat tapping a laptop, or something like that (not sure if buffer let's you do gifs?)
- Saturday has two tweets, not sure we need that! Maybe move one of those to a different day 
All in all, good job!

**Comment by rzahabi** [comment]
Edits are done!
